disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - no_fallthrough_only
  - function_parameter_count
  - orphaned_doc_comment
  - type_body_length
  - file_length

included: 
  - Sources
excluded:
  - Sources/Classes/ObjCExceptionCatcher
  - Tests
  - Example
 
force_cast: warning

line_length: 256

identifier_name:
  excluded:
    - itu709_2
    - itu2020_hlg
    - itu2020_pq
    - uhd
    - fhd
    - hd
    - sd
    - from
    - to
    - id
