disabled_rules:
  - cyclomatic_complexity
  - function_body_length

included: 
  - Sources
excluded:
  - Sources/Classes/ObjCExceptionCatcher
  - Tests
  - Example
 
force_cast: warning

line_length: 256

type_body_length:
  warning: 600 
  error: 800

file_length:
  warning: 1000
  error: 1250

identifier_name:
  excluded:
    - itu709_2
    - itu2020_hlg
    - itu2020_pq
    - uhd
    - fhd
    - hd
    - sd