disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - no_fallthrough_only
  - function_parameter_count
  - orphaned_doc_comment

included: 
  - Sources
excluded:
  - Sources/Classes/ObjCExceptionCatcher
  - Tests
  - Example
 
force_cast: warning

line_length: 256

type_body_length:
  warning: 800 
  error: 1000

file_length:
  warning: 1500
  error: 2000

identifier_name:
  excluded:
    - itu709_2
    - itu2020_hlg
    - itu2020_pq
    - uhd
    - fhd
    - hd
    - sd
    - from
    - to
    - id
